#ifndef H_ED_DQ_20050122153658
#define H_ED_DQ_20050122153658

#ifdef __cplusplus
extern "C"
{
#endif

/* ---------------------------------------------------------------------
   (c) ED 2005
   Project      : CLIB
   Function     : Double linked list
   Module       : DQ
   File         : dq.h
   Created      : 22-01-2005
   Modified     : 22-01-2005
   --------------------------------------------------------------------- */

/* ---------------------------------------------------------------------
   Log

   0.0 22-01-2005 Created
   1.0 22-01-2005 Initial version

   --------------------------------------------------------------------- */
#include <stddef.h>

/* macros ============================================================== */

/* constants =========================================================== */

typedef enum
{
   DQ_OK,

#define ITEM(n_, s_)\
   DQ_ERR_##n_,

#include "ed/inc/dq_err.itm"

#undef ITEM

   DQ_ERR_NB
}
dq_err_e;

/* types =============================================================== */

typedef int dq_list_f (void *p_user, void *p_data);

/* structures ========================================================== */

typedef struct dq dq_s;

/* functions =========================================================== */

/* Identification */
char const * dq_sid (void);
char const * dq_sver (void);

/* Dynamic constructor / destructor */
dq_s * dq_create (void);
void dq_delete (dq_s * self);


dq_err_e dq_getsize (dq_s * self, size_t * p_nb);
dq_err_e dq_addtail (dq_s * self, void *v, size_t siz);
dq_err_e dq_addhead (dq_s * self, void *v, size_t siz);

void *dq_getcurrent (dq_s * self);
dq_err_e dq_clear (dq_s * self);
dq_err_e dq_next (dq_s * self);
dq_err_e dq_prev (dq_s * self);
dq_err_e dq_remove (dq_s * self, void *v, size_t siz);
dq_err_e dq_list (dq_s * self, int rev, dq_list_f * pf, void *p_user);


#ifdef __cplusplus
}
#endif

/* ---------------------------------------------------------------------
   Generated by NEW (c) ED 2.5
   Powered by C-code generator (c) ED 2003 1.0
   --------------------------------------------------------------------- */

#endif /* guard */
